### PR TITLE
Feature#2

### PR DESCRIPTION
**Pull request by josephwithay**
Created a new branch for feature 2. Review my changes and confirm it.
Signed-off-by:josephwithay yoseph_jo@hotmail.com

### CODE REVIEW

**Comment by kennethtran93** [comment]
Alrighty - thanks for the first controller comment fix.

**Comment by kennethtran93** [comment]
i guess the readme will just get updated with no visual changes whatsoever

**Comment by josephwithay** [comment]
I think so

**Comment by josephwithay** [comment]
is it all good?

**Comment by kennethtran93** [comment]
why is it that the signed-off by is missing in some commits?

**Comment by josephwithay** [comment]
maybe because im using git desktop to commit??

**Comment by kennethtran93** [comment]
not netbeans?

## 

Kenneth Tran
kennethtran93@gmail.com

**Comment by kennethtran93** [comment]
try checking your git desktop config...

**Comment by josephwithay** [comment]
i prefer that because i see my changes right there

**Comment by kennethtran93** [comment]
there's a function in netbeans git for that...

**Comment by kennethtran93** [comment]
double-check your git desktop config to see an option for signed-off-by...

**Comment by josephwithay** [comment]
so are you going to confirm my PR?

**Comment by kennethtran93** [comment]
i'll accept it this time since at least one of your commits has a signed-off portion.

for future commits outside of netbeans ensure you tag on a --s or --signoff as referenced here: http://schacon.github.io/git/git-commit.html

**Comment by kennethtran93** [comment]
From new branch: Good
Signed: Good enough...
Formatting: Good
Changelog: Good
Does it work: Yes.

PR Approved

**Pull request merged**
